package org.finance.business.entity.templates.accountting.system;

import org.finance.business.entity.Report;
import org.finance.business.entity.ReportFormula;
import org.finance.business.entity.Subject;
import org.finance.business.entity.enums.Symbol;
import org.finance.infrastructure.constants.LendingDirection;

import java.util.Arrays;
import java.util.List;

/**
 * @author jiangbangfa
 */
public class N1 extends AbstractSystem {

    public N1() {
        subjects = Arrays.asList(
                new Subject("1001", "库存现金", Subject.Category.ASSETS,  LendingDirection.BORROW, true),
                new Subject("1002", "银行存款", Subject.Category.ASSETS,  LendingDirection.BORROW, true),
                new Subject("1012", "其他货币资金", Subject.Category.ASSETS,  LendingDirection.BORROW, true),
                new Subject("1101", "短期投资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("110101", "股票", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("110102", "债券", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("110103", "基金", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("110110", "其他", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1121", "应收票据", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1122", "应收账款", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1123", "预付账款", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1131", "应收股利", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1132", "应收利息", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1221", "其他应收款", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1401", "材料采购", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1402", "在途物资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1403", "原材料", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1404", "材料成本差异", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1405", "库存商品", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1407", "商品进销差价", Subject.Category.ASSETS,  LendingDirection.LOAN, false),
                new Subject("1408", "委托加工物资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1411", "周转材料", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1421", "消耗性生物资产", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1501", "长期债券投资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("150101", "债券投资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("150102", "其他债权投资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1511", "长期股权投资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("151101", "股票投资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("151102", "其他股权投资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1601", "固定资产", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1602", "累计折旧", Subject.Category.ASSETS,  LendingDirection.LOAN, false),
                new Subject("1604", "在建工程", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("160401", "建筑工程", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("160402", "安装工程", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("160403", "技术改造工程", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("160404", "其他支出", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1605", "工程物资", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1606", "固定资产清理", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1621", "生产性生物资产", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1622", "生产性生物资产累计折旧", Subject.Category.ASSETS,  LendingDirection.LOAN, false),
                new Subject("1701", "无形资产", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1702", "累计摊销", Subject.Category.ASSETS,  LendingDirection.LOAN, false),
                new Subject("1801", "长期待摊费用", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("1901", "待处理财产损溢", Subject.Category.ASSETS,  LendingDirection.BORROW, false),
                new Subject("2001", "短期借款", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2201", "应付票据", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2202", "应付账款", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2203", "预收账款", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2211", "应付职工薪酬", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2221", "应交税费", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222101", "应交增值税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("22210101", "进项税额", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("22210102", "销项税额的抵减", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("22210103", "已交税金", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("22210104", "转出未交增值税", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("22210105", "减免税款", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("22210106", "出口抵减内销产品应纳税额", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("22210107", "销项税额", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("22210108", "出口退税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("22210109", "进项税额转出", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("22210110", "转出多交增值税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222102", "未交增值税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222103", "预交增值税", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("222104", "待抵扣进项税额", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("222105", "待认证进项税额", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("222106", "待转销项税额", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222107", "增值税留抵税额", Subject.Category.FU_ZAI,  LendingDirection.BORROW, false),
                new Subject("222108", "简易计税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222109", "转让金融商品应交增值税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222110", "代扣代交增值税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222111", "应交所得税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222112", "应交个人所得税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222113", "教育费附加", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222114", "地方教育费附加", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222115", "应交资源税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222116", "应交土地增值税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222117", "应交城市维护建设税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222118", "应交房产税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222119", "应交土地使用税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("222120", "应交车船使用税", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2231", "应付利息", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2232", "应付利润", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2241", "其他应付款", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2401", "递延收益", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2501", "长期借款", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("2701", "长期应付款", Subject.Category.FU_ZAI,  LendingDirection.LOAN, false),
                new Subject("3001", "实收资本", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("3002", "资本公积", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("300201", "资本溢价", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("300202", "接受捐赠非现金资产准备", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("300206", "外币资本折算差额", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("300207", "其他资本公积", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("3101", "盈余公积", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("310101", "法定盈余公积", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("310102", "任意盈余公积", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("310103", "法定公益金", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("3103", "本年利润", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("3104", "利润分配", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("310401", "其他转入", Subject.Category.EQUITY,  LendingDirection.BORROW, false),
                new Subject("310402", "提取法定盈余公积", Subject.Category.EQUITY,  LendingDirection.BORROW, false),
                new Subject("310403", "提取法定公益金", Subject.Category.EQUITY,  LendingDirection.BORROW, false),
                new Subject("310409", "提取任意盈余公积", Subject.Category.EQUITY,  LendingDirection.BORROW, false),
                new Subject("310410", "应付利润", Subject.Category.EQUITY,  LendingDirection.BORROW, false),
                new Subject("310411", "转作资本的利润", Subject.Category.EQUITY,  LendingDirection.BORROW, false),
                new Subject("310415", "未分配利润", Subject.Category.EQUITY,  LendingDirection.LOAN, false),
                new Subject("4001", "生产成本", Subject.Category.COST,  LendingDirection.BORROW, false),
                new Subject("400101", "基本生产成本", Subject.Category.COST,  LendingDirection.BORROW, false),
                new Subject("400102", "辅助生产成本", Subject.Category.COST,  LendingDirection.BORROW, false),
                new Subject("4101", "制造费用", Subject.Category.COST,  LendingDirection.BORROW, false),
                new Subject("4301", "研发支出", Subject.Category.COST,  LendingDirection.BORROW, false),
                new Subject("4401", "工程施工", Subject.Category.COST,  LendingDirection.BORROW, false),
                new Subject("4403", "机械作业", Subject.Category.COST,  LendingDirection.BORROW, false),
                new Subject("5001", "主营业务收入", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("5051", "其他业务收入", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("5111", "投资收益", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("5301", "营业外收入", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("530101", "非流动资产处置净收益", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("530102", "政府补助", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("530103", "捐赠收益", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("530104", "盘盈收益", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("530105", "其他", Subject.Category.PROFIT,  LendingDirection.LOAN, false),
                new Subject("5401", "主营业务成本", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("5402", "其他业务成本", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("5403", "税金及附加", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540301", "消费税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540302", "税金及附加_营业税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540303", "城市维护建设税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540304", "资源税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540305", "土地增值税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540306", "城镇土地使用税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540307", "房产税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540308", "车船税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540309", "印花税", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540310", "教育费附加", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540311", "矿产资源补偿费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540312", "排污费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("540313", "地方教育费附加", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("5601", "销售费用", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560101", "办公用品", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560102", "房租", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560103", "物业管理费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560104", "水电费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560105", "交际应酬费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560106", "市内交通费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560107", "差旅费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560108", "补助", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560109", "通讯费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560110", "工资", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560111", "佣金", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560112", "保险金", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560113", "福利费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560114", "累计折旧", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560115", "商品维修费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560116", "广告和业务宣传费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560199", "其他", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("5602", "管理费用", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560201", "办公用品", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560202", "房租", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560203", "物业管理费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560204", "水电费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560205", "交际应酬费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560206", "市内交通费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560207", "差旅费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560208", "通讯费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560209", "工资", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560210", "保险金", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560211", "福利费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560212", "累计折旧", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560213", "开办费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560214", "职工教育经费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560215", "研究费用", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560299", "其他", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("5603", "财务费用", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560301", "汇兑损益", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560302", "利息", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560303", "手续费", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("560399", "其他", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("5711", "营业外支出", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571101", "存货盘亏毁损", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571102", "非流动资产处置净损失", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571103", "坏账损失", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571104", "无法收回的长期债券投资损失", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571105", "无法收回的长期股权投资损失", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571106", "自然灾害等不可抗力造成的损失", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571107", "税收滞纳金", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571108", "罚金、罚款", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571109", "捐赠支出", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("571110", "其他", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("5801", "所得税费用", Subject.Category.PROFIT,  LendingDirection.BORROW, false),
                new Subject("6000", "以前年度损益调整", Subject.Category.PROFIT,  LendingDirection.BORROW, false)
        );
        reports = Arrays.asList(
                /**
                 * 资产负债表1~100
                 */
                new Report(1, Report.Category.ASSETS, "流动资产：", 0, 1, 0),
                new Report(2, Report.Category.ASSETS, "货币资金", 1,2, 1).buildBalanceFormulas("1001", "1002", "1012"),
                new Report(3, Report.Category.ASSETS, "短期投资", 2, 2, 1).buildBalanceFormulas("1101"),
                new Report(4, Report.Category.ASSETS, "应收票据", 3, 2, 1).buildBalanceFormulas("1121"),
                new Report(5, Report.Category.ASSETS, "应收账款", 4, 2, 1).buildBalanceFormulas("1122"),
                new Report(6, Report.Category.ASSETS, "预付账款", 5, 2, 1).buildBalanceFormulas("1123"),
                new Report(7, Report.Category.ASSETS, "应收股利", 6, 2, 1).buildBalanceFormulas("1131"),
                new Report(8, Report.Category.ASSETS, "应收利息", 7, 2, 1).buildBalanceFormulas("1132"),
                new Report(9, Report.Category.ASSETS, "其他应收款",8, 2, 1).buildBalanceFormulas("1221"),
                new Report(10, Report.Category.ASSETS, "存货",9, 2, 1).buildBalanceFormulas("1401","1402","1403","1404","1405","1407","1408","1411","1421","4001","4101","4401","4403"),
                new Report(11, Report.Category.ASSETS, "其中：原材料",10, 3, 1).buildBalanceFormulas("1403", "1404"),
                new Report(12, Report.Category.ASSETS, "在产品",11, 3, 1).buildBalanceFormulas("4001","4101","4401","4403"),
                new Report(13, Report.Category.ASSETS, "库存商品",12, 3, 1).buildBalanceFormulas("1405", "1407"),
                new Report(14, Report.Category.ASSETS, "周转材料",13, 3, 1).buildBalanceFormulas("1411"),
                new Report(15, Report.Category.ASSETS, "其他流动资产",14, 2, 1),
                new Report(16, Report.Category.ASSETS, "流动资产合计",15, 2, 2).buildAggregateFormulas(2, 3,4,5,6,7,8,9,10, 15),
                new Report(17, Report.Category.ASSETS, "非流动资产：", 0,1, 0),
                new Report(18, Report.Category.ASSETS, "长期债券投资",16, 2, 1).buildBalanceFormulas("1501"),
                new Report(19, Report.Category.ASSETS, "长期股权投资",17, 2, 1).buildBalanceFormulas("1511"),
                new Report(20, Report.Category.ASSETS, "固定资产原价",18, 2, 1).buildBalanceFormulas("1601"),
                new Report(21, Report.Category.ASSETS, "减：累计折旧",19, 2, 1).buildBalanceFormulas("1602"),
                new Report(22, Report.Category.ASSETS, "固定资产账面价值",20, 2, 1).buildMinusBalanceFormulas("1601", "1602"),
                new Report(23, Report.Category.ASSETS, "在建工程",21, 2, 1).buildBalanceFormulas("1604"),
                new Report(24, Report.Category.ASSETS, "工程物资",22, 2, 1).buildBalanceFormulas("1605"),
                new Report(25, Report.Category.ASSETS, "固定资产清理", 23, 2, 1).buildBalanceFormulas("1606"),
                new Report(26, Report.Category.ASSETS, "生产性生物资产",24, 2, 1).buildBalanceFormulas("1621", "1622"),
                new Report(27, Report.Category.ASSETS, "无形资产",25, 2, 1).buildBalanceFormulas("1701", "1702"),
                new Report(28, Report.Category.ASSETS, "开发支出",26, 2, 1).buildBalanceFormulas("4301"),
                new Report(29, Report.Category.ASSETS, "长期待摊费用",27, 2, 1).buildBalanceFormulas("1801"),
                new Report(30, Report.Category.ASSETS, "其他非流动资产",28, 2, 1).buildBalanceFormulas("1901"),
                new Report(31, Report.Category.ASSETS, "非流动资产合计",29, 2, 2).buildAggregateFormulas(18, 19, 22, 23, 24, 25, 26, 27, 28, 29, 30),
                new Report(32, Report.Category.ASSETS, "资产总计",30, 1, 3).buildAggregateFormulas(16, 31),

                new Report(51, Report.Category.ASSETS, "流动负债：", 0,1, 0),
                new Report(52, Report.Category.ASSETS, "短期借款", 31,2, 1).buildBalanceFormulas("2001"),
                new Report(53, Report.Category.ASSETS, "应付票据", 32,2, 1).buildBalanceFormulas("2201"),
                new Report(54, Report.Category.ASSETS, "应付账款", 33,2, 1).buildBalanceFormulas("2202"),
                new Report(55, Report.Category.ASSETS, "预收账款", 34,2, 1).buildBalanceFormulas("2203"),
                new Report(56, Report.Category.ASSETS, "应付职工薪酬", 35,2, 1).buildBalanceFormulas("2211"),
                new Report(57, Report.Category.ASSETS, "应交税费", 36,2, 1).buildBalanceFormulas("2221"),
                new Report(58, Report.Category.ASSETS, "应付利息", 37,2, 1).buildBalanceFormulas("2231"),
                new Report(59, Report.Category.ASSETS, "应付利润", 38,2, 1).buildBalanceFormulas("2232"),
                new Report(60, Report.Category.ASSETS, "其他应付款", 39,2, 1).buildBalanceFormulas("2241"),
                new Report(61, Report.Category.ASSETS, "其他流动负债", 40,2, 1),
                new Report(62, Report.Category.ASSETS, "流动负债合计：", 41,2, 2).buildAggregateFormulas(52, 53, 54, 55, 56, 57 ,58, 59, 60, 61),
                new Report(63, Report.Category.ASSETS, "非流动负债：", 0,1, 0),
                new Report(64, Report.Category.ASSETS, "长期借款", 42,2, 1).buildBalanceFormulas("2501"),
                new Report(65, Report.Category.ASSETS, "长期应付款", 43,2, 1).buildBalanceFormulas("2701"),
                new Report(66, Report.Category.ASSETS, "递延收益", 44,2, 1).buildBalanceFormulas("2401"),
                new Report(67, Report.Category.ASSETS, "其他非流动负债", 45,2, 1),
                new Report(68, Report.Category.ASSETS, "非流动负债合计", 46,2, 2).buildAggregateFormulas(64, 65, 66, 67),
                new Report(69, Report.Category.ASSETS, "负债合计", 47,2, 3).buildAggregateFormulas(62, 68),
                new Report(76, Report.Category.ASSETS, "所有者权益（或股东权益）：", 0,1, 0),
                new Report(77, Report.Category.ASSETS, "实收资本（或股本）", 48,2, 1).buildBalanceFormulas("3001"),
                new Report(78, Report.Category.ASSETS, "资本公积", 49,2, 1).buildBalanceFormulas("3002"),
                new Report(79, Report.Category.ASSETS, "盈余公积", 50,2, 1).buildBalanceFormulas("3101"),
                new Report(80, Report.Category.ASSETS, "未分配利润", 51,2, 1).buildBalanceFormulas("3103", "3104"),
                new Report(81, Report.Category.ASSETS, "所有者权益（或股东权益）合计", 52,2, 2).buildAggregateFormulas(77, 78, 79, 80),
                new Report(82, Report.Category.ASSETS, "负债和所有者权益（或股东权益）总计", 53,1, 3).buildAggregateFormulas(69, 81),
                /**
                 * 利润表101~200
                 */
                new Report(101, Report.Category.PROFIT, "一、营业收入", 1,1, 1).buildAmountFormulas("5001", "5051"),
                new Report(102, Report.Category.PROFIT, "减：营业成本", 2,1, 1).buildAmountFormulas("5401", "5402"),
                new Report(103, Report.Category.PROFIT, "税金及附加", 3,2, 1).buildAmountFormulas("5403"),
                new Report(104, Report.Category.PROFIT, "其中：消费税", 4,3, 1).buildAmountFormulas("540301"),
                new Report(105, Report.Category.PROFIT, "营业税", 5,3, 1).buildAmountFormulas("540302"),
                new Report(106, Report.Category.PROFIT, "城市维护建设税", 6,3, 1).buildAmountFormulas("540303"),
                new Report(107, Report.Category.PROFIT, "资源税", 7,3, 1).buildAmountFormulas("540304"),
                new Report(108, Report.Category.PROFIT, "土地增值税", 8,3, 1).buildAmountFormulas("540305"),
                new Report(109, Report.Category.PROFIT, "城镇土地使用税、房产税、车船税、印花税", 9,3, 1).buildAmountFormulas("540306", "540307", "540308", "540309"),
                new Report(110, Report.Category.PROFIT, "教育费附加、矿产资源补偿税、排污费", 10,3, 1).buildAmountFormulas("540310", "540311", "540312"),
                new Report(111, Report.Category.PROFIT, "销售费用", 11,2, 1).buildAmountFormulas("5601"),
                new Report(112, Report.Category.PROFIT, "其中：商品维修费", 12,2, 1).buildAmountFormulas("560215"),
                new Report(113, Report.Category.PROFIT, "广告费和业务宣传费", 13,3, 1).buildAmountFormulas("560216"),
                new Report(114, Report.Category.PROFIT, "管理费用", 14,2, 1).buildAmountFormulas("5602"),
                new Report(115, Report.Category.PROFIT, "其中：开办费", 15,2, 1).buildAmountFormulas("560213"),
                new Report(116, Report.Category.PROFIT, "业务招待费", 16,3, 1).buildAmountFormulas("560205"),
                new Report(117, Report.Category.PROFIT, "研究费用", 17,3, 1).buildAmountFormulas("560215"),
                new Report(118, Report.Category.PROFIT, "财务费用", 18,2, 1).buildAmountFormulas("5603"),
                new Report(119, Report.Category.PROFIT, "其中：利息费用（收入以“-”号填列）", 19,2, 1).buildAmountFormulas("560301"),
                new Report(120, Report.Category.PROFIT, "加：投资收益（损失以“-”号填列）", 20,1, 1).buildAmountFormulas("5111"),
                new Report(121, Report.Category.PROFIT, "二、营业利润（亏损以“-”号填列）", 21,1, 1).setReportFormulas(Arrays.asList(
                        new ReportFormula(Symbol.ADD, "5001", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5051", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5111", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5401", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5402", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5403", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5601", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5602", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5603", ReportFormula.NumberRule.AMOUNT)
                )),
                new Report(122, Report.Category.PROFIT, "加：营业外收入", 22,1, 1).buildAmountFormulas("5301"),
                new Report(123, Report.Category.PROFIT, "其中：政府补助", 23,2, 1).buildAmountFormulas("530102"),
                new Report(124, Report.Category.PROFIT, "减：营业外支出", 24,1, 1).buildAmountFormulas("5711"),
                new Report(125, Report.Category.PROFIT, "其中：坏账损失", 25,2, 1).buildAmountFormulas("571103"),
                new Report(126, Report.Category.PROFIT, "无法收回的长期债券投资损失", 26,3, 1).buildAmountFormulas("571104"),
                new Report(127, Report.Category.PROFIT, "无法收回的长期股权投资损失", 27,3, 1).buildAmountFormulas("571105"),
                new Report(128, Report.Category.PROFIT, "自然灾害等不可抗力因素造成的损失", 28,3, 1).buildAmountFormulas("571106"),
                new Report(129, Report.Category.PROFIT, "税收滞纳金", 29,3, 1).buildAmountFormulas("571107"),
                new Report(130, Report.Category.PROFIT, "三、利润总额（亏损总额以“-”号填列）", 30,1, 1).setReportFormulas(Arrays.asList(
                        new ReportFormula(Symbol.ADD, "5001", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5051", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5111", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5301", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5401", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5402", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5403", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5601", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5602", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5602", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5711", ReportFormula.NumberRule.AMOUNT)
                )),
                new Report(131, Report.Category.PROFIT, "减：所得税费用", 31,1, 1).buildAmountFormulas("5801"),
                new Report(132, Report.Category.PROFIT, "四：净利润（净亏损以“-”号填列 ", 32,1, 1).setReportFormulas(Arrays.asList(
                        new ReportFormula(Symbol.ADD, "5001", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5051", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5111", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.ADD, "5301", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5401", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5402", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5403", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5601", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5602", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5602", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5711", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "5801", ReportFormula.NumberRule.AMOUNT)
                )),
                /**
                 * 现金流量表
                 */
                new Report(201, Report.Category.CASH_FLOW, "一、经营活动产生的现金流量：", 0, 1, 0),
                new Report(202, Report.Category.CASH_FLOW, "销售产成品、商品、提供劳务收到的现金", 1, 2, 1),
                new Report(203, Report.Category.CASH_FLOW, "收到其他与经营活动有关的现金", 2, 2, 1),
                new Report(204, Report.Category.CASH_FLOW, "购买原材料、商品、接受劳务支付的现金", 3, 2, 1),
                new Report(205, Report.Category.CASH_FLOW, "支付的职工薪酬", 4, 2, 1),
                new Report(206, Report.Category.CASH_FLOW, "支付的税费", 5, 2, 1),
                new Report(207, Report.Category.CASH_FLOW, "支付其他与经营活动有关的现金", 6, 2, 1),
                new Report(208, Report.Category.CASH_FLOW, "经营活动产生的现金流量净额", 7, 2, 1),
                new Report(209, Report.Category.CASH_FLOW, "二、投资活动产生的现金流量：", 0, 1, 0),
                new Report(210, Report.Category.CASH_FLOW, "收回短期投资、长期债券投资和长期股权投资收到的现金", 8, 2, 1),
                new Report(211, Report.Category.CASH_FLOW, "取得投资收益收到的现金", 9, 2, 1),
                new Report(212, Report.Category.CASH_FLOW, "处置固定资产、无形资产和其他非流动资产收回的现金净额", 10, 2, 1),
                new Report(213, Report.Category.CASH_FLOW, "短期投资、长期债券投资和长期股权投资支付的现金", 11, 2, 1),
                new Report(214, Report.Category.CASH_FLOW, "购建固定资产、无形资产和其他非流动资产支付的现金", 12, 2, 1),
                new Report(215, Report.Category.CASH_FLOW, "投资活动产生的现金流量净额", 0, 13, 1),
                new Report(216, Report.Category.CASH_FLOW, "三、筹资活动产生的现金流量：", 0, 1, 0),
                new Report(217, Report.Category.CASH_FLOW, "取得借款收到的现金", 14, 2, 1),
                new Report(218, Report.Category.CASH_FLOW, "吸收投资者投资收到的现金", 15, 2, 1),
                new Report(219, Report.Category.CASH_FLOW, "偿还借款本金支付的现金", 16, 2, 1),
                new Report(220, Report.Category.CASH_FLOW, "偿还借款利息支付的现金", 17, 2, 1),
                new Report(221, Report.Category.CASH_FLOW, "分配利润支付的现金", 18, 2, 1),
                new Report(222, Report.Category.CASH_FLOW, "筹资活动产生的现金流量净额", 19, 2, 1),
                new Report(223, Report.Category.CASH_FLOW, "四、现金净增加额", 20, 1, 1),
                new Report(224, Report.Category.CASH_FLOW, "加：期初现金余额", 21, 1, 1),
                new Report(225, Report.Category.CASH_FLOW, "五、期末现金余额", 22, 1, 1)
        );
        initial();
    }

    @Override
    public List<Subject> getSubjects() {
        return this.subjects;
    }

    @Override
    public List<Report> getReports() {
        return this.reports;
    }

}
