package org.finance.business.entity.templates.accountting.system;

import org.finance.business.entity.AggregateFormula;
import org.finance.business.entity.Report;
import org.finance.business.entity.ReportFormula;
import org.finance.business.entity.Subject;
import org.finance.business.entity.enums.Symbol;
import org.finance.infrastructure.constants.LendingDirection;

import java.util.Arrays;
import java.util.List;

/**
 * @author jiangbangfa
 */
public class N4 extends AbstractSystem {

    public N4() {
        this.subjects = Arrays.asList(
                new Subject("1001", "库存现金", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("1002", "银行存款", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("1012", "其他货币资金", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("101201", "外埠存款", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("101202", "银行本票存款", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("101203", "银行汇票存款", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("101204", "信用卡存款", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("101205", "信用证保证金存款", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("101206", "存出投资款", Subject.Category.ASSETS, LendingDirection.BORROW, true),
                new Subject("1101", "交易性金融资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("110101", "本金", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010101", "股票", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010102", "债券", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010103", "基金", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010104", "权证", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010199", "其他", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("110102", "公允价值变动", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010201", "股票", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010202", "债券", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010203", "基金", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010204", "权证", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("11010299", "其他", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1121", "应收票据", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1122", "应收账款", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1123", "预付账款", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1131", "应收股利", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1132", "应收利息", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1221", "其他应收款", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1231", "坏账准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("123101", "应收账款坏账准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("123102", "其他应收款坏账准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1321", "受托代销商品", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1401", "材料采购", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1402", "在途物资", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1403", "原材料", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1404", "材料成本差异", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1405", "库存商品", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1406", "发出商品", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1407", "商品进销差价", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1408", "委托加工物资", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1411", "周转材料", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1412", "应收退货成本", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1462", "合同资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1463", "合同资产减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1464", "合同结算", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("146401", "价款结算", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("146402", "收入结转", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1465", "合同取得成本", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1466", "合同取得成本减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1467", "合同履约成本", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1468", "合同履约成本减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1471", "存货跌价准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1481", "持有待售资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1482", "持有待售资产减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1501", "债权投资", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1502", "债权投资减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1503", "其他债权投资", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1504", "其他权益工具投资", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1511", "长期股权投资", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("151101", "投资成本", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("151102", "损益调整", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("151103", "所有者权益其他变动", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1512", "长期股权投资减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1521", "投资性房地产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("152101", "成本", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("152102", "公允价值变动", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1531", "长期应收款", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1532", "未实现融资收益", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1601", "固定资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1602", "累计折旧", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1603", "固定资产减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1604", "在建工程", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160401", "建筑工程", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160402", "安装工程", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160403", "在安装设备", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160404", "待摊支出", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1605", "工程物资", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160501", "专用材料", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160502", "专用设备", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160503", "预付大型设备款", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("160504", "为生产准备的工具及器具", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1606", "固定资产清理", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1607", "使用权资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1608", "使用权资产累计折旧", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1609", "使用权资产减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1621", "生产性生物资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1622", "生产性生物资产累计折旧", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1701", "无形资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1702", "累计摊销", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1703", "无形资产减值准备", Subject.Category.ASSETS, LendingDirection.LOAN, false),
                new Subject("1711", "商誉", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1801", "长期待摊费用", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1811", "递延所得税资产", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("1901", "待处理财产损溢", Subject.Category.ASSETS, LendingDirection.BORROW, false),
                new Subject("2001", "短期借款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2101", "交易性金融负债", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("210101", "本金", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("210102", "公允价值变动", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2201", "应付票据", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2202", "应付账款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2203", "预收账款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2204", "合同负债", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2211", "应付职工薪酬", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("221101", "工资", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("221102", "职工福利", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("221103", "社会保险费", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("221104", "住房公积金", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("221105", "工会经费", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("221106", "职工教育经费", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("221107", "解除职工劳动关系补偿", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2221", "应交税费", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222101", "应交增值税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("22210101", "进项税额", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("22210102", "销项税额抵减", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("22210103", "已交税金", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("22210104", "转出未交增值税", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("22210105", "减免税款", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("22210106", "出口抵减内销产品应纳税额", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("22210107", "销项税额", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("22210108", "出口退税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("22210109", "进项税额转出", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("22210110", "转出多交增值税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222102", "未交增值税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222103", "预交增值税", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("222104", "待抵扣进项税额", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("222105", "待认证进项税额", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("222106", "待转销项税额", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222107", "增值税留抵税额", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("222108", "简易计税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222109", "转让金融商品应交增值税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222110", "代扣代交增值税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222111", "应交所得税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222112", "应交个人所得税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222113", "应交教育费附加", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222114", "应交城市维护建设税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222115", "应交地方教育费附加", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222116", "应交土地增值税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222117", "应交资源税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222118", "应交房产税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222119", "应交土地使用税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222120", "应交车船使用税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222121", "应交消费税", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("222122", "应交矿产资源补偿费", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2231", "应付股利", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2232", "应付利息", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2241", "其他应付款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2245", "持有待售负债", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2314", "受托代銷商品款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2401", "递延收益", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2501", "长期借款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("250101", "本金", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("250102", "利息调整", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2502", "应付债券", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("250201", "优先股", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("250202", "永续债", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("250203", "其他", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2601", "租赁负债", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2701", "长期应付款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2702", "未确认融资费用", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("2711", "专项应付款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2801", "预计负债", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("280101", "应付退货款", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("280102", "贷款承诺", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("280103", "财务担保", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("2901", "递延所得税负债", Subject.Category.FU_ZAI, LendingDirection.LOAN, false),
                new Subject("3101", "衍生工具", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("3201", "套期工具", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("3202", "被套期项目", Subject.Category.FU_ZAI, LendingDirection.BORROW, false),
                new Subject("4001", "实收资本", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("4002", "资本公积", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("400201", "资本溢价", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("400202", "股本溢价", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("400203", "其他资本公积", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("4003", "其他综合收益", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("400301", "信用减值准备", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("400302", "套期储备", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("4101", "盈余公积", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("410101", "法定盈余公积", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("410102", "任意盈余公积", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("410103", "法定公益金", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("410104", "储备基金", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("410105", "企业发展基金", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("410106", "利润归还投资", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("4103", "本年利润", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("4104", "利润分配", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("410401", "提取法定盈余公积", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410402", "提取任意盈余公积", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410403", "提取法定公益金", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410404", "应付现金股利或利润", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410405", "转作股本的利润", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410406", "盈余公积补亏", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410407", "提取储备基金", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410408", "提取企业发展基金", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410409", "提取职工奖励及福利基金", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410410", "利润归还投资", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("410411", "未分配利润", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("4201", "库存股", Subject.Category.EQUITY, LendingDirection.BORROW, false),
                new Subject("4301", "专项储备", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("4401", "其他权益工具", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("440101", "优先股", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("440102", "永续债", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("440103", "其他", Subject.Category.EQUITY, LendingDirection.LOAN, false),
                new Subject("5001", "生产成本", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("500101", "基本生产成本", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("500102", "辅助生产成本", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("5101", "制造费用", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("5201", "劳务成本", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("5301", "研发支出", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("530101", "费用化支出", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("530102", "资本化支出", Subject.Category.COST, LendingDirection.BORROW, false),
                new Subject("6001", "主营业务收入", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6051", "其他业务收入", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6101", "公允价值变动损益", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6111", "投资收益", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6115", "其他收益", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("611501", "政府补助", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("611502", "扣缴税款手续费", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("611599", "其他", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6117", "资产处置损益", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6118", "净敞口套期收益", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6301", "营业外收入", Subject.Category.PROFIT, LendingDirection.LOAN, false),
                new Subject("6401", "主营业务成本", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6402", "其他业务成本", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6403", "税金及附加", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("640301", "房产税", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("640302", "车船使用税", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("640303", "土地使用税", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("640304", "印花税", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6601", "销售费用", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660101", "办公用品", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660102", "房租", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660103", "物业管理费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660104", "水电费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660105", "交际应酬费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660106", "市内交通费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660107", "差旅费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660108", "补助", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660109", "通讯费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660110", "工资", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660111", "佣金", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660112", "保险金", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660113", "福利费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660114", "包装费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660115", "展览费和广告费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660116", "商品维修费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660117", "预计产品质量保证损失", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660118", "运输费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660119", "装卸费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660120", "折旧费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660121", "计提福利", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660122", "计提职工教育经费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660199", "其他", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6602", "管理费用", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660201", "办公用品", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660202", "房租", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660203", "物业管理费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660204", "水电费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660205", "交际应酬费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660206", "市内交通费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660207", "差旅费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660208", "通讯费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660209", "工资", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660210", "保险金", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660211", "福利费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660212", "工会经费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660213", "董事会费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660214", "聘请中介机构费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660215", "咨询费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660216", "诉讼费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660217", "技术转让费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660218", "矿产资源补偿费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660219", "研发费用", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660220", "无形资产摊销", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660221", "排污费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660222", "折旧费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660223", "计提福利", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660224", "计提职工教育经费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660225", "存货盘亏或盘盈", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660299", "其他", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6603", "财务费用", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660301", "汇兑损益", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660302", "利息费用", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660303", "手续费", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660304", "利息收入", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("660399", "其他", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6701", "资产减值损失", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6702", "信用减值损失", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6711", "营业外支出", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6801", "所得税", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("680101", "当期所得税费用", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("680102", "递延所得税费用", Subject.Category.PROFIT, LendingDirection.BORROW, false),
                new Subject("6901", "以前年度损益调整", Subject.Category.PROFIT, LendingDirection.BORROW, false)
        );
        this.reports = Arrays.asList(
                /**
                 * 资产负债表
                 */
                new Report(1, Report.Category.ASSETS, "流动资产：", 0, 1, 0),
                new Report(2, Report.Category.ASSETS, "货币资金", 1, 2, 1).buildBalanceFormulas("1001", "1002", "1012"),
                new Report(3, Report.Category.ASSETS, "交易性金融资产", 2, 2, 1).buildBalanceFormulas("1101"),
                new Report(4, Report.Category.ASSETS, "衍生金融资产", 3, 2, 1).buildBalanceFormulas("3101"),
                new Report(5, Report.Category.ASSETS, "应收票据", 4, 2, 1).buildBalanceFormulas("1121"),
                new Report(6, Report.Category.ASSETS, "应收账款", 5, 2, 1).buildBalanceFormulas("1122", "113101"),
                new Report(7, Report.Category.ASSETS, "应收款项融资", 6, 2, 1),
                new Report(8, Report.Category.ASSETS, "预付款项", 7, 2, 1).buildBalanceFormulas("1123"),
                new Report(9, Report.Category.ASSETS, "其他应收款", 8, 2, 1).buildBalanceFormulas("1131", "1221", "123102", "1132"),
                new Report(10, Report.Category.ASSETS, "存货", 9, 2, 1).buildBalanceFormulas("468", "1471", "5001", "5101", "5201"),
                new Report(11, Report.Category.ASSETS, "合同资产", 10, 2, 1).setReportFormulas(Arrays.asList(
                        new ReportFormula(Symbol.ADD, "1462", ReportFormula.NumberRule.BALANCE),
                        new ReportFormula(Symbol.ADD, "1463", ReportFormula.NumberRule.BALANCE),
                        new ReportFormula(Symbol.MINUS, "1464", ReportFormula.NumberRule.CREDIT_BALANCE)
                )),
                new Report(12, Report.Category.ASSETS, "持有待售资产", 11, 2, 1).buildBalanceFormulas("1481", "1482"),
                new Report(13, Report.Category.ASSETS, "一年内到期的非流动资产", 12, 2, 1),
                new Report(14, Report.Category.ASSETS, "其他流动资产", 13, 2, 1).buildBalanceFormulas("1465", "1466"),
                new Report(15, Report.Category.ASSETS, "流动资产合计", 14, 2, 2).buildAggregateFormulas(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14),
                new Report(16, Report.Category.ASSETS, "非流动资产：", 0, 1, 0),
                new Report(17, Report.Category.ASSETS, "债权投资", 15, 2, 1).buildBalanceFormulas("1501", "1502"),
                new Report(18, Report.Category.ASSETS, "其他债权投资", 16, 2, 1).buildBalanceFormulas("1503"),
                new Report(19, Report.Category.ASSETS, "长期应收款", 17, 2, 1).buildBalanceFormulas("1531"),
                new Report(20, Report.Category.ASSETS, "长期股权投资", 18, 2, 1).buildBalanceFormulas("1511", "1512"),
                new Report(21, Report.Category.ASSETS, "其他权益工具投资", 19, 2, 1).buildBalanceFormulas("1504"),
                new Report(22, Report.Category.ASSETS, "其他非流动金融资产", 20, 2, 1),
                new Report(23, Report.Category.ASSETS, "投资性房地产", 21, 2, 1).buildBalanceFormulas("1521"),
                new Report(24, Report.Category.ASSETS, "固定资产", 22, 2, 1).buildBalanceFormulas("1601", "1602", "1603", "1606"),
                new Report(25, Report.Category.ASSETS, "在建工程", 23, 2, 1).buildBalanceFormulas("1604", "1605"),
                new Report(26, Report.Category.ASSETS, "生产性生物资产", 24, 2, 1).buildBalanceFormulas("1621", "1622"),
                new Report(27, Report.Category.ASSETS, "油气资产", 25, 2, 1),
                new Report(28, Report.Category.ASSETS, "使用权资产", 26, 2, 1).buildBalanceFormulas("1607", "1608", "1609"),
                new Report(29, Report.Category.ASSETS, "无形资产", 27, 2, 1).buildBalanceFormulas("1701", "1702", "1703"),
                new Report(30, Report.Category.ASSETS, "开发支出", 28, 2, 1).buildBalanceFormulas("5301"),
                new Report(31, Report.Category.ASSETS, "商誉", 29, 2, 1).buildBalanceFormulas("1711"),
                new Report(32, Report.Category.ASSETS, "长期待摊费用", 30, 2, 1).buildBalanceFormulas("1801"),
                new Report(33, Report.Category.ASSETS, "递延所得税资产", 31, 2, 1).buildBalanceFormulas("1811"),
                new Report(34, Report.Category.ASSETS, "其他非流动资产", 32, 2, 1).buildBalanceFormulas("1532", "1901"),
                new Report(35, Report.Category.ASSETS, "非流动资产合计", 33, 2, 2).buildAggregateFormulas(17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34),
                new Report(41, Report.Category.ASSETS, "资产总计", 34, 1, 3).buildAggregateFormulas(15, 35),

                new Report(51, Report.Category.ASSETS, "流动负债：", 0, 1, 0),
                new Report(52, Report.Category.ASSETS, "短期借款", 35, 2, 1).buildBalanceFormulas("2001"),
                new Report(53, Report.Category.ASSETS, "交易性金融负债", 36, 2, 1).buildBalanceFormulas("2101"),
                new Report(54, Report.Category.ASSETS, "衍生金融负债", 37, 2, 1).buildBalanceFormulas("3101"),
                new Report(55, Report.Category.ASSETS, "应付票据", 38, 2, 1).buildBalanceFormulas("2201"),
                new Report(56, Report.Category.ASSETS, "应付账款", 39, 2, 1).buildBalanceFormulas("2202"),
                new Report(57, Report.Category.ASSETS, "预收款项", 40, 2, 1).buildBalanceFormulas("2203"),
                new Report(58, Report.Category.ASSETS, "合同负债", 41, 2, 1).setReportFormulas(Arrays.asList(
                        new ReportFormula(Symbol.ADD, "2204", ReportFormula.NumberRule.BALANCE),
                        new ReportFormula(Symbol.ADD, "1464", ReportFormula.NumberRule.CREDIT_BALANCE)
                )),
                new Report(59, Report.Category.ASSETS, "应付职工薪酬", 42, 2, 1).buildBalanceFormulas("2211"),
                new Report(60, Report.Category.ASSETS, "应交税费", 43, 2, 1).buildBalanceFormulas("2221"),
                new Report(61, Report.Category.ASSETS, "其他应付款", 44, 2, 1).buildBalanceFormulas("2231", "2231", "2241"),
                new Report(62, Report.Category.ASSETS, "持有待售负债", 45, 2, 1).buildBalanceFormulas("2245"),
                new Report(63, Report.Category.ASSETS, "一年内到期的非流动负债", 46, 2, 1),
                new Report(64, Report.Category.ASSETS, "其他流动负债", 47, 2, 1).buildBalanceFormulas("2314"),
                new Report(65, Report.Category.ASSETS, "流动负债合计", 48, 2, 2).buildAggregateFormulas(52,53,54,55,56,57,58,59,60,61,62,63,64),
                new Report(66, Report.Category.ASSETS, "非流动负债：", 0, 1, 0),
                new Report(67, Report.Category.ASSETS, "长期借款", 49, 2, 1).buildBalanceFormulas("2501"),
                new Report(68, Report.Category.ASSETS, "应付债券", 50, 2, 1).buildBalanceFormulas("2502"),
                new Report(69, Report.Category.ASSETS, "其中：优先股", 51, 2, 1).buildBalanceFormulas("250201"),
                new Report(70, Report.Category.ASSETS, "永续债", 52, 3, 1).buildBalanceFormulas("250202"),
                new Report(71, Report.Category.ASSETS, "租赁负债", 53, 2, 1).buildBalanceFormulas("2601"),
                new Report(72, Report.Category.ASSETS, "长期应付款", 54, 2, 1).buildBalanceFormulas("2701","2702","2711"),
                new Report(73, Report.Category.ASSETS, "预计负债", 55, 2, 1).buildBalanceFormulas("2801"),
                new Report(74, Report.Category.ASSETS, "递延收益", 56, 2, 1).buildBalanceFormulas("2401"),
                new Report(75, Report.Category.ASSETS, "递延所得税负债", 57, 2, 1).buildBalanceFormulas("2901"),
                new Report(76, Report.Category.ASSETS, "其他非流动负债", 58, 2, 1),
                new Report(77, Report.Category.ASSETS, "非流动负债合计", 59, 2, 2).buildAggregateFormulas(67,68,71,72,73,74,75),
                new Report(78, Report.Category.ASSETS, "负债合计 ", 60, 1, 1).buildAggregateFormulas(65,77),
                new Report(79, Report.Category.ASSETS, "所有者权益（或股东权益）：", 0, 1, 0),
                new Report(80, Report.Category.ASSETS, "实收资本（或股本", 61, 2, 1).buildBalanceFormulas("4001"),
                new Report(81, Report.Category.ASSETS, "其他权益工具", 62, 2, 1).buildBalanceFormulas("4401"),
                new Report(82, Report.Category.ASSETS, "其中：优先股", 63, 2, 1).buildBalanceFormulas("440101"),
                new Report(83, Report.Category.ASSETS, "永续债", 64, 3, 1).buildBalanceFormulas("440102"),
                new Report(84, Report.Category.ASSETS, "资本公积", 65, 2, 1).buildBalanceFormulas("4002"),
                new Report(85, Report.Category.ASSETS, "减：库存股", 66, 2, 1).buildBalanceFormulas("4201"),
                new Report(86, Report.Category.ASSETS, "其他综合收益", 67, 2, 1).buildBalanceFormulas("4003"),
                new Report(87, Report.Category.ASSETS, "专项储备", 68, 2, 1).buildBalanceFormulas("4301"),
                new Report(88, Report.Category.ASSETS, "盈余公积", 69, 2, 1).buildBalanceFormulas("4101"),
                new Report(89, Report.Category.ASSETS, "未分配利润", 70, 2, 1).buildBalanceFormulas("4103", "4104"),
                new Report(90, Report.Category.ASSETS, "所有者权益（或股东权益）合计", 71, 2, 2).buildAggregateFormulas(80,81,84,85,86,87,88,89),
                new Report(91, Report.Category.ASSETS, "负债和所有者权益（或股东权益）总计", 72, 1, 3).buildAggregateFormulas(78, 90),

                /**
                 * 利润表
                 */
                new Report(101, Report.Category.PROFIT, "一、营业收入", 1, 1, 1).buildAmountFormulas("6001", "6051"),
                new Report(102, Report.Category.PROFIT, "减：营业成本", 2, 2, 1).buildAmountFormulas("6401", "6402"),
                new Report(103, Report.Category.PROFIT, "税金及附加", 3, 3, 1).buildAmountFormulas("6403"),
                new Report(104, Report.Category.PROFIT, "销售费用", 4, 4, 1).buildAmountFormulas("6601"),
                new Report(105, Report.Category.PROFIT, "管理费用", 5, 4, 1).setReportFormulas(Arrays.asList(
                        new ReportFormula(Symbol.ADD, "6602", ReportFormula.NumberRule.AMOUNT),
                        new ReportFormula(Symbol.MINUS, "660219", ReportFormula.NumberRule.AMOUNT)
                )),
                new Report(106, Report.Category.PROFIT, "研发费用", 6, 4, 1).buildAmountFormulas("660219"),
                new Report(107, Report.Category.PROFIT, "财务费用", 7, 4, 1).buildAmountFormulas("6603"),
                new Report(108, Report.Category.PROFIT, "其中：利息费用", 8, 4, 1).buildAmountFormulas("660302"),
                new Report(109, Report.Category.PROFIT, "利息收入", 9, 5, 1).buildAmountFormulas("660304"),
                new Report(110, Report.Category.PROFIT, "加：其他收益", 10, 2, 1),
                new Report(111, Report.Category.PROFIT, "投资收益（损失以“-”号填列）", 11, 1, 1).buildAmountFormulas("6111"),
                new Report(112, Report.Category.PROFIT, "其中：对联营企业和合营企业的投资收益", 12, 3, 1),
                new Report(113, Report.Category.PROFIT, "以摊余成本计量的金融资产终止确认收益（损失以“-”号填列）", 13, 3, 1),
                new Report(114, Report.Category.PROFIT, "净敞口套期收益（损失以“-”号填列）", 14, 3, 1).buildAmountFormulas("6118"),
                new Report(115, Report.Category.PROFIT, "公允价值变动收益（损失以“-”号填列）", 15, 3, 1).buildAmountFormulas("6101"),
                new Report(116, Report.Category.PROFIT, "信用减值损失（损失以“-”号填列）", 16, 3, 1).buildAmountFormulas("6702"),
                new Report(117, Report.Category.PROFIT, "资产减值损失（损失以“-”号填列）", 17, 3, 1).buildAmountFormulas("6701"),
                new Report(118, Report.Category.PROFIT, "资产处置收益（损失以“-”号填列）", 18, 3, 1).buildAmountFormulas("6117"),
                new Report(119, Report.Category.PROFIT, "二、营业利润（亏损以“-”号填列）", 19, 1, 1).setAggregateFormulas(Arrays.asList(
                        new AggregateFormula(Symbol.ADD, 101),
                        new AggregateFormula(Symbol.MINUS, 102),
                        new AggregateFormula(Symbol.MINUS, 103),
                        new AggregateFormula(Symbol.MINUS, 104),
                        new AggregateFormula(Symbol.MINUS, 105),
                        new AggregateFormula(Symbol.MINUS, 106),
                        new AggregateFormula(Symbol.MINUS, 107),
                        new AggregateFormula(Symbol.ADD, 111),
                        new AggregateFormula(Symbol.ADD, 114),
                        new AggregateFormula(Symbol.ADD, 115),
                        new AggregateFormula(Symbol.ADD, 116),
                        new AggregateFormula(Symbol.ADD, 117),
                        new AggregateFormula(Symbol.ADD, 118)
                )),
                new Report(120, Report.Category.PROFIT, "加：营业外收入", 20, 2, 1).buildAmountFormulas("6301"),
                new Report(121, Report.Category.PROFIT, "减：营业外支出", 21, 2, 1).buildAmountFormulas("6711"),
                new Report(122, Report.Category.PROFIT, "三、利润总额（亏损总额以“-”号填列）", 22, 1, 1).setAggregateFormulas(Arrays.asList(
                        new AggregateFormula(Symbol.ADD, 119),
                        new AggregateFormula(Symbol.ADD, 120),
                        new AggregateFormula(Symbol.MINUS, 121)
                )),
                new Report(123, Report.Category.PROFIT, "减：所得税费用", 23, 2, 1).buildAmountFormulas("6801"),
                new Report(124, Report.Category.PROFIT, "四、净利润（净亏损以“-”号填列）", 24, 1, 1).setAggregateFormulas(Arrays.asList(
                        new AggregateFormula(Symbol.ADD, 122),
                        new AggregateFormula(Symbol.MINUS, 123)
                )),
                new Report(125, Report.Category.PROFIT, "（一）持续经营净利润（净亏损以“-”号填列）", 25, 2, 1),
                new Report(126, Report.Category.PROFIT, "（二）终止经营净利润（净亏损以“-”号填列）", 26, 2, 1),
                new Report(127, Report.Category.PROFIT, "五、其他综合收益的税后净额", 27, 1, 1),
                new Report(128, Report.Category.PROFIT, "（一）不能重分类进损益的其他综合收益", 28, 2, 1),
                new Report(129, Report.Category.PROFIT, "1. 重新计量设定受益计划变动额", 29, 3, 1),
                new Report(130, Report.Category.PROFIT, "2. 权益法下不能转损益的其他综合收益", 30, 3, 1),
                new Report(131, Report.Category.PROFIT, "3. 其他权益工具投资公允价值变动", 31, 3, 1),
                new Report(132, Report.Category.PROFIT, "4. 企业自身信用风险公允价值变动", 32, 3, 1),
                new Report(133, Report.Category.PROFIT, "……", 0, 1, 1),
                new Report(134, Report.Category.PROFIT, "（二）将重分类进损益的其他综合收益", 33, 2, 1),
                new Report(135, Report.Category.PROFIT, "1. 权益法下可转损益的其他综合收益", 34, 3, 1),
                new Report(136, Report.Category.PROFIT, "2. 其他债权投资公允价值变动", 35, 3, 1),
                new Report(137, Report.Category.PROFIT, "3. 金融资产重分类计入其他综合收益的金额", 36, 3, 1),
                new Report(138, Report.Category.PROFIT, "4. 其他债权投资信用减值准备", 37, 3, 1),
                new Report(139, Report.Category.PROFIT, "5. 现金流量套期储备", 38, 3, 1),
                new Report(140, Report.Category.PROFIT, "6. 外币财务报表折算差额", 39, 3, 1),
                new Report(141, Report.Category.PROFIT, "……", 0, 1, 1),
                new Report(142, Report.Category.PROFIT, "六、综合收益总额", 40, 1, 1),
                new Report(143, Report.Category.PROFIT, "七、每股收益", 41, 1, 1),
                new Report(144, Report.Category.PROFIT, "（一）基本每股收益", 42, 2, 1),
                new Report(145, Report.Category.PROFIT, "（二）稀释每股收益", 43, 2, 1),
                /**
                 * 现金流量表
                 */
                new Report(201, Report.Category.CASH_FLOW, "一、经营活动产生的现金流量：", 0, 1, 1),
                new Report(202, Report.Category.CASH_FLOW, "销售商品、提供劳务收到的现金", 1, 1, 1),
                new Report(203, Report.Category.CASH_FLOW, "收到的税费返还", 2, 1, 1),
                new Report(204, Report.Category.CASH_FLOW, "收到其他与经营活动有关的现金", 3, 1, 1),
                new Report(205, Report.Category.CASH_FLOW, "经营活动现金流入小计", 4, 1, 1),
                new Report(206, Report.Category.CASH_FLOW, "购买商品、接受劳务支付的现金", 5, 1, 1),
                new Report(207, Report.Category.CASH_FLOW, "支付给职工以及为职工支付的现金", 6, 1, 1),
                new Report(208, Report.Category.CASH_FLOW, "支付的各项税费", 7, 1, 1),
                new Report(209, Report.Category.CASH_FLOW, "支付其他与经营活动有关的现金", 8, 1, 1),
                new Report(210, Report.Category.CASH_FLOW, "经营活动现金流出小计", 9, 1, 1),
                new Report(211, Report.Category.CASH_FLOW, "经营活动产生的现金流量净额", 10, 1, 1),
                new Report(212, Report.Category.CASH_FLOW, "二、投资活动产生的现金流量：", 0, 1, 1),
                new Report(213, Report.Category.CASH_FLOW, "收回投资收到的现金", 11, 1, 1),
                new Report(214, Report.Category.CASH_FLOW, "取得投资收益收到的现金", 12, 1, 1),
                new Report(215, Report.Category.CASH_FLOW, "处置固定资产、无形资产和其他长期资产收回的现金净额", 13, 1, 1),
                new Report(216, Report.Category.CASH_FLOW, "处置子公司及其他营业单位收到的现金净额", 14, 1, 1),
                new Report(217, Report.Category.CASH_FLOW, "收到其他与投资活动有关的现金", 15, 1, 1),
                new Report(218, Report.Category.CASH_FLOW, "投资活动现金流入小计", 16, 1, 1),
                new Report(219, Report.Category.CASH_FLOW, "购建固定资产、无形资产和其他长期资产支付的现金", 17, 1, 1),
                new Report(220, Report.Category.CASH_FLOW, "投资支付的现金", 18, 1, 1),
                new Report(221, Report.Category.CASH_FLOW, "取得子公司及其他营业单位支付的现金净额", 19, 1, 1),
                new Report(222, Report.Category.CASH_FLOW, "支付其他与投资活动有关的现金", 20, 1, 1),
                new Report(223, Report.Category.CASH_FLOW, "投资活动现金流出小计", 21, 1, 1),
                new Report(224, Report.Category.CASH_FLOW, "投资活动产生的现金流量净额", 22, 1, 1),
                new Report(225, Report.Category.CASH_FLOW, "三、筹资活动产生的现金流量：", 0, 1, 1),
                new Report(226, Report.Category.CASH_FLOW, "吸收投资收到的现金", 23, 1, 1),
                new Report(227, Report.Category.CASH_FLOW, "取得借款收到的现金", 24, 1, 1),
                new Report(228, Report.Category.CASH_FLOW, "收到其他与筹资活动有关的现金", 25, 1, 1),
                new Report(229, Report.Category.CASH_FLOW, "筹资活动现金流入小计", 26, 1, 1),
                new Report(230, Report.Category.CASH_FLOW, "偿还债务支付的现金", 27, 1, 1),
                new Report(231, Report.Category.CASH_FLOW, "分配股利、利润或偿付利息支付的现金", 28, 1, 1),
                new Report(232, Report.Category.CASH_FLOW, "支付其他与筹资活动有关的现金", 29, 1, 1),
                new Report(233, Report.Category.CASH_FLOW, "筹资现金流出小计", 30, 1, 1),
                new Report(234, Report.Category.CASH_FLOW, "筹资活动产生的现金流量净额", 31, 1, 1),
                new Report(235, Report.Category.CASH_FLOW, "四、汇率变动对现金及现金等价物的影响", 32, 1, 1),
                new Report(236, Report.Category.CASH_FLOW, "五、现金及现金等价物净增加额", 33, 1, 1),
                new Report(237, Report.Category.CASH_FLOW, "加：期初现金及现金等价物余额", 34, 1, 1),
                new Report(238, Report.Category.CASH_FLOW, "六、期末现金及现金等价物余额", 35, 1,1)
        );
        initial();
    }

    @Override
    public List<Subject> getSubjects() {
        return this.subjects;
    }

    @Override
    public List<Report> getReports() {
        return this.reports;
    }

}
