version: "3.6"

services:
  backend:
    build: .
    command:
      [
          sh,
          -c,
          'java -Duser.timezone=GMT+08:00 $JAVA_OPTS -Dspring.profiles.active=local -Djava.security.egd=file:/dev/./urandom -jar /app.jar',
      ]
    volumes:
      - /d/workspace/data/app/finance-backend/log/:/var/log
      - /d/workspace/data/app/finance-backend/tmp/:/tmp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/finance?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_PASSWORD=root1997
      - SPRING_REDIS_HOST=redis
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESSKEY=jiangbangfa
      - MINIO_SECRETKEY=jiangbangfa
      - TZ=Asia/Shanghai
    ports:
      - "8081:8081"
    restart: always
    networks:
      - internal_network
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    restart: always
    networks:
      - internal_network
#  mysql:
#    image: mysql:5.7.18
#    volumes:
#      - /d/workspace/data/mysql/:/var/lib/mysql/
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ROOT_PASSWORD=root1997
#      - MYSQL_DATABASE=finance
#    ports:
#      - "3306:3306"
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
#    restart: always
#    networks:
#      - internal_network
  minio:
    image: "minio/minio"
    command: [ server, "/data", "--console-address", ":9001" ]
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
      - "MINIO_ROOT_USER=jiangbangfa"
      - "MINIO_ROOT_PASSWORD=jiangbangfa"
    volumes:
      - /d/workspace/data/minio:/data
    networks:
      - internal_network
networks:
  internal_network:
    name: internal_network