spring:
  application:
    name: finance-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
#  activiti:
#    check-process-definitions: false
#    database-schema: act
#    jpa-enabled: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      update-strategy: not_null
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
